language: php

php:
    - 5.3

before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5
    - echo "Alias /behatch $(pwd)/fixtures/www" | sudo tee -a /etc/apache2/sites-available/default
    - sudo /etc/init.d/apache2 restart
    - sed 's/%hostname%/localhost\/behatch/' behat.yml-dist > behat.yml
    - sed 's/%hostname%/localhost\/behatch/' fixtures/www/xml/feed.xml-dist > fixtures/www/xml/feed.xml
    - curl http://getcomposer.org/installer | php
    - php composer.phar install --dev

script: ./bin/behat --tags='~@javascript&&~@user'
